apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267158693:role/eksctl-expense-nodegroup-expense-m-NodeInstanceRole-ccFxIkyPzniS
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::533267158693:user/EKSClusterRBACUser
      username: EKSClusterRBACUser
kind: ConfigMap
metadata:
  creationTimestamp: "2024-12-14T12:25:14Z"
  name: aws-auth
  namespace: kube-system
  uid: 0b83671e-56ce-41b2-8bed-2589e1bf048f #don't delete this

## mapUsers:
## - groups: - system: name of the Role which we created in rbac.yaml
## userarn: you need to give your ARN for IAM user from AWS console.
## username: name of the IAM user created for the EKS cluster describe access.
